#!/bin/bash

#### START EXPORTS ####

# colored terminal
export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad

# golang specific
export GOPATH=/Users/SakuraSound/Developer/Golang
export GOBIN=$GOPATH/bin

export FIGLET_FONTS=/usr/local/Cellar/figlet/2.2.5/share/figlet/fonts

# actual path variable
export PATH=$PATH:$GOBIN

if [ -z "$LAST_UPDATE" ] ; then
    true
else
    LAST_UPDATE=$(date +%Y-%m-%d)
    export $LAST_UPDATE
fi

# Docker based exports
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.100:2376"
export DOCKER_CERT_PATH="/Users/SakuraSound/.docker/machine/machines/default"
export DOCKER_MACHINE_NAME="default"

####  END EXPORTS  ####
